#1

In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
cidades = pd.read_excel('BRCidadesRegiao.xlsx')
cidades

,Unnamed: 0.2,Unnamed: 0,Unnamed: 0.1,municipio,codigo,area_territorial,populacao_estimada,densidade_demografica,escolarizacao,idhm,...,GVA_industria,GVA_Servicos,GVA_publico,GDP,GDP_populacao,GDP_per_capita,estabelecimentos,carros,motos,regiao_imediata
0,0,0,0,Açailândia,2100055,5808.304,113121,17.92,97.7,0.672,...,488799.22,779.84,364811.85,1999546.31,110543,18088.40,1334,9935.0,24208.0,AP de Imperatriz/MA
1,1,1,1,Afonso Cunha,2100105,371.338,6578,15.90,96.6,0.529,...,1600.00,8.46,21500.22,35459.24,6421,5522.39,14,61.0,519.0,AP de Teresina/PI
2,2,2,2,Água Doce do Maranhão,2100154,443.267,12652,26.13,98.3,0.500,...,3555.39,19612.05,39464.68,73287.14,12360,5929.38,57,61.0,495.0,Parnaíba
3,3,3,3,Alcântara,2100204,1168.246,22112,14.70,96.8,0.573,...,7861.43,29391.33,61419.05,117494.58,21667,5422.74,124,327.0,1282.0,AP de São Luís/MA
4,4,4,4,Aldeias Altas,2100303,1942.121,26757,12.33,94.9,0.513,...,9704.76,38558.93,81.62,169251.79,26115,6481.02,91,327.0,2271.0,Caxias
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531,5531,5531,5955,Pacaraima,1400456,8025.045,18913,1.30,93.0,0.650,...,8161.28,29966.90,114622.75,164518.39,12144,13547.30,108,979.0,379.0,Boa Vista
5532,5532,5532,5956,Rorainópolis,1400472,33579.739,30782,0.72,95.5,0.619,...,36173.93,97.97,262297.53,506131.66,27756,18235.04,264,1214.0,3990.0,Boa Vista
5533,5533,5533,5957,São João da Baliza,1400506,4284.505,8348,1.58,93.6,0.655,...,10158.54,26606.34,74719.19,140.28,7629,18387.38,42,262.0,1441.0,Boa Vista
5534,5534,5534,5958,São Luiz,1400605,1526.898,8110,4.42,92.0,0.649,...,4084.71,15.87,70184.88,110589.67,7503,14739.39,51,257.0,1244.0,Boa Vista
5535,5535,5535,5959,Uiramutã,1400704,8113.598,10789,1.04,60.2,0.453,...,1189.55,4.75,87.28,103680.32,9664,10728.51,8,7.0,25.0,Boa Vista

In [3]:
cidades = cidades[['regiao_imediata', 'cidade', 'estado', 'longitude', 'latitude', 'altitude',
'area_territorial', 'populacao_estimada', 'densidade_demografica', 'pib_per_capita', 'receitas_realizadas',
'despesas_empenhadas', 'saldo_receitas_despesas', 'unidades', 'unidades_urbanas', 'unidades_rurais', 'area_plantada', 'producao_graos',
'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'GVA_agropecuaria', 'GVA_industria', 'GVA_Servicos', 'GVA_publico',
'GDP', 'GDP_populacao', 'GDP_per_capita', 'estabelecimentos', 'carros', 'motos'
]].copy()

In [4]:
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5536 entries, 0 to 5535
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   regiao_imediata          5536 non-null   object
 1   cidade                   5536 non-null   object
 2   estado                   5536 non-null   object
 3   longitude                5529 non-null   float64
 4   latitude                 5529 non-null   float64
 5   altitude                 5529 non-null   float64
 6   area_territorial         5536 non-null   float64
 7   populacao_estimada       5536 non-null   int64
 8   densidade_demografica    5531 non-null   float64
 9   pib_per_capita           5536 non-null   float64
 10  receitas_realizadas      5514 non-null   float64
 11  despesas_empenhadas      5514 non-null   float64
 12  saldo_receitas_despesas  5514 non-null   float64
 13  unidades                 5529 non-null   float64
 14  unidades_urbanas         5529 non-null   float64
 15  unidades_rurais          5458 non-null   float64
 16  area_plantada            5536 non-null   int64
 17  producao_graos           5536 non-null   int64
 18  IDHM_Renda               5530 non-null   float64
 19  IDHM_Longevidade         5530 non-null   float64
 20  IDHM_Educacao            5530 non-null   float64
 21  GVA_agropecuaria         5536 non-null   float64
 22  GVA_industria            5536 non-null   float64
 23  GVA_Servicos             5536 non-null   float64
 24  GVA_publico              5536 non-null   float64
 25  GDP                      5536 non-null   float64
 26  GDP_populacao            5536 non-null   int64
 27  GDP_per_capita           5536 non-null   float64
 28  estabelecimentos         5536 non-null   int64
 29  carros                   5528 non-null   float64
 30  motos                    5528 non-null   float64
dtypes: float64(23), int64(5), object(3)
memory usage: 1.3+ MB

In [5]:
cidades.replace([np.inf, -np.inf], np.nan, inplace=True)
cidades.dropna(inplace=True)
cidades

,regiao_imediata,cidade,estado,longitude,latitude,altitude,area_territorial,populacao_estimada,densidade_demografica,pib_per_capita,...,GVA_agropecuaria,GVA_industria,GVA_Servicos,GVA_publico,GDP,GDP_populacao,GDP_per_capita,estabelecimentos,carros,motos
0,AP de Imperatriz/MA,Açailândia,MA,-47.506665,-4.951377,229.05,5808.304,113121,17.92,19780.01,...,159853.84,488799.22,779.84,364811.85,1999546.31,110543,18088.40,1334,9935.0,24208.0
1,AP de Teresina/PI,Afonso Cunha,MA,-43.320869,-4.135015,67.20,371.338,6578,15.90,6934.67,...,2461.41,1600.00,8.46,21500.22,35459.24,6421,5522.39,14,61.0,519.0
2,Parnaíba,Água Doce do Maranhão,MA,-42.115551,-2.840278,10.44,443.267,12652,26.13,5895.85,...,8.10,3555.39,19612.05,39464.68,73287.14,12360,5929.38,57,61.0,495.0
3,AP de São Luís/MA,Alcântara,MA,-44.417013,-2.403277,29.72,1168.246,22112,14.70,5387.80,...,14464.15,7861.43,29391.33,61419.05,117494.58,21667,5422.74,124,327.0,1282.0
4,Caxias,Aldeias Altas,MA,-43.468735,-4.630779,80.49,1942.121,26757,12.33,6614.18,...,31.99,9704.76,38558.93,81.62,169251.79,26115,6481.02,91,327.0,2271.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529,Boa Vista,Mucajaí,RR,-60.911519,2.479772,69.63,12337.851,18172,1.19,17804.20,...,39103.32,13137.27,47561.62,156797.76,270.95,16618,16304.33,129,867.0,2480.0
5530,Boa Vista,Normandia,RR,-59.635206,3.882978,102.78,6959.868,11532,1.28,14108.20,...,16966.21,2.26,11743.00,97667.78,129666.02,10339,12541.45,18,140.0,432.0
5532,Boa Vista,Rorainópolis,RR,-60.425060,0.937195,83.80,33579.739,30782,0.72,18832.65,...,62063.98,36173.93,97.97,262297.53,506131.66,27756,18235.04,264,1214.0,3990.0
5533,Boa Vista,São João da Baliza,RR,-59.906044,0.947157,121.25,4284.505,8348,1.58,20041.66,...,13886.89,10158.54,26606.34,74719.19,140.28,7629,18387.38,42,262.0,1441.0
5534,Boa Vista,São Luiz,RR,-60.028267,1.018112,116.35,1526.898,8110,4.42,15710.68,...,16533.59,4084.71,15.87,70184.88,110589.67,7503,14739.39,51,257.0,1244.0

In [6]:
cidades['estado'].unique()

array(['MA', 'RS', 'BA', 'PR', 'ES', 'MT', 'AC', 'TO', 'SE', 'PA', 'PI',
       'GO', 'SC', 'CE', 'AP', 'RO', 'MS', 'AM', 'MG', 'PE', 'DF', 'RN',
       'SP', 'AL', 'PB', 'RJ', 'RR'], dtype=object)

In [7]:
cidades_SC = cidades[cidades['estado'] == 'SC'].copy()
cidades_SC

,regiao_imediata,cidade,estado,longitude,latitude,altitude,area_territorial,populacao_estimada,densidade_demografica,pib_per_capita,...,GVA_agropecuaria,GVA_industria,GVA_Servicos,GVA_publico,GDP,GDP_populacao,GDP_per_capita,estabelecimentos,carros,motos
2580,AP de Joaçaba - Herval d´Oeste/SC,Abdon Batista,SC,-51.025272,-27.608987,720.98,237.517,2548,11.25,24214.96,...,24996.75,3578.87,16011.10,17842.64,64742.01,2617,24739.02,69,976.0,345.0
2581,AP de Chapecó/SC,Abelardo Luz,SC,-52.336482,-26.563031,724.99,953.992,17960,17.94,33976.15,...,212531.45,78176.47,197092.10,78972.10,604280.35,17782,33982.70,464,5823.0,2001.0
2582,AP de Rio do Sul/SC,Agrolândia,SC,-49.825653,-27.400517,383.22,206.815,11013,44.92,22980.77,...,36.18,55228.22,75110.21,43981.83,225.80,10427,21655.48,490,4218.0,2146.0
2583,AP de Rio do Sul/SC,Agronômica,SC,-49.718369,-27.269716,342.19,129.774,5509,37.57,28610.56,...,47908.44,22249.14,35.73,24434.96,138390.31,5371,25766.21,223,2135.0,903.0
2584,AP de Joaçaba - Herval d´Oeste/SC,Água Doce,SC,-51.559097,-27.004092,806.11,1319.137,7152,5.30,41691.56,...,141254.65,28806.01,91540.21,35489.48,317937.56,7143,44510.37,216,2740.0,692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,AP de Rio do Sul/SC,Witmarsum,SC,-49.804203,-26.926743,400.08,153.776,3998,23.69,30881.48,...,32530.04,24244.13,27380.92,18927.65,108907.83,3876,28098.00,205,1550.0,771.0
2870,Xanxerê,Xanxerê,SC,-52.404667,-26.874585,787.90,377.426,51642,116.81,32237.14,...,96.16,293442.51,773709.41,197061.43,1528009.92,49057,31147.64,2495,20613.0,6838.0
2871,Xanxerê,Xavantina,SC,-52.342851,-27.070250,516.80,218.032,3903,19.12,45607.66,...,58590.04,52789.99,41540.50,20222.17,186210.16,4039,46103.03,165,1226.0,390.0
2872,AP de Chapecó/SC,Xaxim,SC,-52.534933,-26.963719,770.95,293.628,28983,87.67,32943.06,...,78.31,247053.53,301228.89,123829.06,844980.07,27921,30263.25,1093,11262.0,3905.0
2873,AP de Joaçaba - Herval d´Oeste/SC,Zortéa,SC,-51.549566,-27.450251,685.30,190.179,3398,15.77,20936.02,...,23859.52,2764.90,19340.06,18019.16,66998.29,3264,20526.44,76,1077.0,359.0

In [8]:
vif_dt = cidades_SC[[
'area_territorial', 'populacao_estimada', 'densidade_demografica', 'pib_per_capita', 'receitas_realizadas',
'despesas_empenhadas', 'saldo_receitas_despesas', 'unidades', 'unidades_urbanas', 'unidades_rurais', 'area_plantada', 'producao_graos',
'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'GVA_agropecuaria', 'GVA_industria', 'GVA_Servicos', 'GVA_publico',
'GDP', 'GDP_populacao', 'GDP_per_capita', 'estabelecimentos', 'carros', 'motos'
]]
vif_dt

,area_territorial,populacao_estimada,densidade_demografica,pib_per_capita,receitas_realizadas,despesas_empenhadas,saldo_receitas_despesas,unidades,unidades_urbanas,unidades_rurais,...,GVA_agropecuaria,GVA_industria,GVA_Servicos,GVA_publico,GDP,GDP_populacao,GDP_per_capita,estabelecimentos,carros,motos
2580,237.517,2548,11.25,24214.96,23228.89256,18399.70671,4829.18585,848.0,234.0,614.0,...,24996.75,3578.87,16011.10,17842.64,64742.01,2617,24739.02,69,976.0,345.0
2581,953.992,17960,17.94,33976.15,62978.76490,54531.83536,8446.92954,4739.0,2694.0,2045.0,...,212531.45,78176.47,197092.10,78972.10,604280.35,17782,33982.70,464,5823.0,2001.0
2582,206.815,11013,44.92,22980.77,31019.33416,28123.29815,2896.03601,2952.0,1927.0,1025.0,...,36.18,55228.22,75110.21,43981.83,225.80,10427,21655.48,490,4218.0,2146.0
2583,129.774,5509,37.57,28610.56,20069.01248,17786.64890,2282.36358,1511.0,589.0,922.0,...,47908.44,22249.14,35.73,24434.96,138390.31,5371,25766.21,223,2135.0,903.0
2584,1319.137,7152,5.30,41691.56,36852.27110,29718.55841,7133.71269,2131.0,1145.0,986.0,...,141254.65,28806.01,91540.21,35489.48,317937.56,7143,44510.37,216,2740.0,692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,153.776,3998,23.69,30881.48,17129.14123,14766.17269,2362.96854,1087.0,260.0,827.0,...,32530.04,24244.13,27380.92,18927.65,108907.83,3876,28098.00,205,1550.0,771.0
2870,377.426,51642,116.81,32237.14,123285.85526,113122.01433,10163.84093,13744.0,12402.0,1342.0,...,96.16,293442.51,773709.41,197061.43,1528009.92,49057,31147.64,2495,20613.0,6838.0
2871,218.032,3903,19.12,45607.66,22896.89996,19119.64225,3777.25771,1179.0,353.0,826.0,...,58590.04,52789.99,41540.50,20222.17,186210.16,4039,46103.03,165,1226.0,390.0
2872,293.628,28983,87.67,32943.06,85997.07298,70477.21407,15519.85891,8075.0,6651.0,1424.0,...,78.31,247053.53,301228.89,123829.06,844980.07,27921,30263.25,1093,11262.0,3905.0
2873,190.179,3398,15.77,20936.02,18213.23233,16591.31060,1621.92173,1026.0,800.0,226.0,...,23859.52,2764.90,19340.06,18019.16,66998.29,3264,20526.44,76,1077.0,359.0

In [9]:
vif_data = pd.DataFrame()
vif_data['variavel'] = vif_dt.columns
vif_data['VIF'] = [variance_inflation_factor(vif_dt.values, i)
    for i in range(len(vif_dt.columns))]
round(vif_data,4)

/usr/local/lib/python3.9/dist-packages/statsmodels/stats/outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

                   variavel           VIF
0          area_territorial  6.286700e+00
1        populacao_estimada  1.352775e+04
2     densidade_demografica  8.597100e+00
3            pib_per_capita  1.208031e+02
4       receitas_realizadas           inf
5       despesas_empenhadas           inf
6   saldo_receitas_despesas           inf
7                  unidades  1.039468e+11
8          unidades_urbanas  9.454590e+10
9           unidades_rurais  5.697636e+08
10            area_plantada  4.453200e+00
11           producao_graos  6.350400e+00
12               IDHM_Renda  9.359272e+02
13         IDHM_Longevidade  7.924254e+02
14            IDHM_Educacao  2.879595e+02
15         GVA_agropecuaria  4.296200e+00
16            GVA_industria  1.095550e+01
17             GVA_Servicos  3.492210e+01
18              GVA_publico  5.208120e+01
19                      GDP  1.826010e+01
20            GDP_populacao  2.498294e+04
21           GDP_per_capita  1.069036e+02
22         estabelecimentos  2.658616e+02
23                   carros  1.269814e+03
24                    motos  5.409290e+01

In [10]:
vif_dt = cidades_SC[[
'area_territorial', 'populacao_estimada', 'pib_per_capita',
'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']]
vif_dt

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
2580,237.517,2548,24214.96,4829.18585,0.625,64742.01
2581,953.992,17960,33976.15,8446.92954,0.578,604280.35
2582,206.815,11013,22980.77,2896.03601,0.633,225.80
2583,129.774,5509,28610.56,2282.36358,0.595,138390.31
2584,1319.137,7152,41691.56,7133.71269,0.574,317937.56
...,...,...,...,...,...,...
2869,153.776,3998,30881.48,2362.96854,0.557,108907.83
2870,377.426,51642,32237.14,10163.84093,0.711,1528009.92
2871,218.032,3903,45607.66,3777.25771,0.632,186210.16
2872,293.628,28983,32943.06,15519.85891,0.662,844980.07
2873,190.179,3398,20936.02,1621.92173,0.661,66998.29

In [11]:
vif_data = pd.DataFrame()
vif_data['variavel'] = vif_dt.columns
vif_data['VIF'] = [variance_inflation_factor(vif_dt.values, i)
    for i in range(len(vif_dt.columns))]
vif_data

                  variavel       VIF
0         area_territorial  2.122522
1       populacao_estimada  6.957170
2           pib_per_capita  6.990777
3  saldo_receitas_despesas  4.454702
4            IDHM_Educacao  7.628575
5                      GDP  5.272037

#2

In [12]:
vif_dt = vif_dt.copy()
for coluna in vif_dt.columns:
    print(coluna)
    out_max = vif_dt[coluna].quantile(0.75) + ((vif_dt[coluna].quantile(0.75) - vif_dt[coluna].quantile(0.25)) * 1.5)
    print(out_max)
    vif_dt[coluna] = vif_dt[coluna].apply(lambda x : out_max if x > out_max else x)
    out_min = vif_dt[coluna].quantile(0.25) - ((vif_dt[coluna].quantile(0.75) - vif_dt[coluna].quantile(0.25)) * 1.5)
    print(out_min)
    vif_dt[coluna] = vif_dt[coluna].apply(lambda x : out_min if x < out_min else x)
vif_dt

area_territorial
756.0722499999999
-230.80374999999998
populacao_estimada
40847.875
-18785.125
pib_per_capita
59385.524999999994
1680.6250000000036
saldo_receitas_despesas
16714.31741500001
-5849.809125000008
IDHM_Educacao
0.7895000000000001
0.4894999999999999
GDP
900274.5812499999
-451315.3287499999

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
2580,237.51700,2548.000,24214.96,4829.18585,0.625,64742.01000
2581,756.07225,17960.000,33976.15,8446.92954,0.578,604280.35000
2582,206.81500,11013.000,22980.77,2896.03601,0.633,225.80000
2583,129.77400,5509.000,28610.56,2282.36358,0.595,138390.31000
2584,756.07225,7152.000,41691.56,7133.71269,0.574,317937.56000
...,...,...,...,...,...,...
2869,153.77600,3998.000,30881.48,2362.96854,0.557,108907.83000
2870,377.42600,40847.875,32237.14,10163.84093,0.711,900274.58125
2871,218.03200,3903.000,45607.66,3777.25771,0.632,186210.16000
2872,293.62800,28983.000,32943.06,15519.85891,0.662,844980.07000
2873,190.17900,3398.000,20936.02,1621.92173,0.661,66998.29000

#3

In [13]:
colunas = ['area_territorial', 'populacao_estimada', 'pib_per_capita', 'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']
sel = colunas
cidadesz = vif_dt[sel].copy()
listaz = []
for coluna in colunas:
    if coluna != "cidade":
        print(coluna)
        listaz.insert(0, 'z_'+coluna)
        media = cidadesz[coluna].mean()
        dp = cidadesz[coluna].std()
        cidadesz['z_'+coluna] = cidadesz[coluna].apply(lambda x : (x - media) / dp)
cidadesz['totalz'] = cidadesz[listaz].sum(axis=1)
cidadesz['ranking'] = cidadesz['totalz'].rank(ascending=False)
cidadesz

area_territorial
populacao_estimada
pib_per_capita
saldo_receitas_despesas
IDHM_Educacao
GDP

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
2580,237.51700,2548.000,24214.96,4829.18585,0.625,64742.01000,-0.278420,-0.838761,-0.648476,-0.264109,-0.180661,-0.694368,-2.904795,203.0
2581,756.07225,17960.000,33976.15,8446.92954,0.578,604280.35000,2.250184,0.350791,0.256248,0.445042,-0.985503,1.080335,3.397096,62.0
2582,206.81500,11013.000,22980.77,2896.03601,0.633,225.80000,-0.428130,-0.185403,-0.762868,-0.643046,-0.043667,-0.906581,-2.969694,208.0
2583,129.77400,5509.000,28610.56,2282.36358,0.595,138390.31000,-0.803801,-0.610221,-0.241067,-0.763338,-0.694390,-0.452116,-3.564932,233.0
2584,756.07225,7152.000,41691.56,7133.71269,0.574,317937.56000,2.250184,-0.483408,0.971357,0.187625,-1.054000,0.138468,2.010225,79.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,153.77600,3998.000,30881.48,2362.96854,0.557,108907.83000,-0.686761,-0.726845,-0.030585,-0.747538,-1.345113,-0.549093,-4.085934,251.0
2870,377.42600,40847.875,32237.14,10163.84093,0.711,900274.58125,0.403811,2.117358,0.095066,0.781591,1.292027,2.053948,6.743801,33.0
2871,218.03200,3903.000,45607.66,3777.25771,0.632,186210.16000,-0.373433,-0.734177,1.334324,-0.470308,-0.060791,-0.294823,-0.599209,125.0
2872,293.62800,28983.000,32943.06,15519.85891,0.662,844980.07000,-0.004808,1.201585,0.160495,1.831479,0.452937,1.872068,5.513755,39.0
2873,190.17900,3398.000,20936.02,1621.92173,0.661,66998.29000,-0.509251,-0.773155,-0.952388,-0.892798,0.435813,-0.686946,-3.378725,223.0

In [14]:
cidades_SC = cidades_SC.merge(cidadesz, right_index=True, left_index=True, how = 'left')
cidades_SC

,regiao_imediata,cidade,estado,longitude,latitude,altitude,area_territorial_x,populacao_estimada_x,densidade_demografica,pib_per_capita_x,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
2580,AP de Joaçaba - Herval d´Oeste/SC,Abdon Batista,SC,-51.025272,-27.608987,720.98,237.517,2548,11.25,24214.96,...,0.625,64742.01000,-0.278420,-0.838761,-0.648476,-0.264109,-0.180661,-0.694368,-2.904795,203.0
2581,AP de Chapecó/SC,Abelardo Luz,SC,-52.336482,-26.563031,724.99,953.992,17960,17.94,33976.15,...,0.578,604280.35000,2.250184,0.350791,0.256248,0.445042,-0.985503,1.080335,3.397096,62.0
2582,AP de Rio do Sul/SC,Agrolândia,SC,-49.825653,-27.400517,383.22,206.815,11013,44.92,22980.77,...,0.633,225.80000,-0.428130,-0.185403,-0.762868,-0.643046,-0.043667,-0.906581,-2.969694,208.0
2583,AP de Rio do Sul/SC,Agronômica,SC,-49.718369,-27.269716,342.19,129.774,5509,37.57,28610.56,...,0.595,138390.31000,-0.803801,-0.610221,-0.241067,-0.763338,-0.694390,-0.452116,-3.564932,233.0
2584,AP de Joaçaba - Herval d´Oeste/SC,Água Doce,SC,-51.559097,-27.004092,806.11,1319.137,7152,5.30,41691.56,...,0.574,317937.56000,2.250184,-0.483408,0.971357,0.187625,-1.054000,0.138468,2.010225,79.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,AP de Rio do Sul/SC,Witmarsum,SC,-49.804203,-26.926743,400.08,153.776,3998,23.69,30881.48,...,0.557,108907.83000,-0.686761,-0.726845,-0.030585,-0.747538,-1.345113,-0.549093,-4.085934,251.0
2870,Xanxerê,Xanxerê,SC,-52.404667,-26.874585,787.90,377.426,51642,116.81,32237.14,...,0.711,900274.58125,0.403811,2.117358,0.095066,0.781591,1.292027,2.053948,6.743801,33.0
2871,Xanxerê,Xavantina,SC,-52.342851,-27.070250,516.80,218.032,3903,19.12,45607.66,...,0.632,186210.16000,-0.373433,-0.734177,1.334324,-0.470308,-0.060791,-0.294823,-0.599209,125.0
2872,AP de Chapecó/SC,Xaxim,SC,-52.534933,-26.963719,770.95,293.628,28983,87.67,32943.06,...,0.662,844980.07000,-0.004808,1.201585,0.160495,1.831479,0.452937,1.872068,5.513755,39.0
2873,AP de Joaçaba - Herval d´Oeste/SC,Zortéa,SC,-51.549566,-27.450251,685.30,190.179,3398,15.77,20936.02,...,0.661,66998.29000,-0.509251,-0.773155,-0.952388,-0.892798,0.435813,-0.686946,-3.378725,223.0

#4

In [18]:
cidades_SC.sort_values(by='ranking')[0:10]

,regiao_imediata,cidade,estado,longitude,latitude,altitude,area_territorial_x,populacao_estimada_x,densidade_demografica,pib_per_capita_x,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
2716,AP de Joinville/SC,Joinville,SC,-48.849409,-26.304518,10.30,1127.946,597658,457.58,47442.90,...,0.7490,900274.58125,2.250184,2.117358,1.504425,2.065617,1.942750,2.053948,11.934281,1.0
2667,AP de Florianópolis/SC,Florianópolis,SC,-48.547637,-27.587796,21.97,674.844,508826,623.68,40162.60,...,0.7895,900274.58125,1.854095,2.117358,0.829644,2.065617,2.636284,2.053948,11.556945,2.0
2822,AP de Joinville/SC,São Francisco do Sul,SC,-48.637571,-26.244018,28.44,493.266,53746,85.27,78766.76,...,0.6990,900274.58125,0.968676,2.117358,2.611337,2.065617,1.086536,2.053948,10.903471,3.0
2636,AP de Joaçaba - Herval d´Oeste/SC,Campos Novos,SC,-51.223673,-27.399053,938.57,1717.697,36556,19.09,55010.59,...,0.6580,900274.58125,2.250184,1.786096,2.205842,2.065617,0.384440,2.053948,10.746127,4.0
2705,AP de Itajaí - Balneário Camboriú/SC,Itajaí,SC,-48.657023,-26.907426,6.37,289.215,223112,636.11,103068.37,...,0.7300,900274.58125,-0.026327,2.117358,2.611337,2.065617,1.617389,2.053948,10.439320,5.0
2616,AP de Blumenau/SC,Blumenau,SC,-49.057631,-26.916108,23.43,518.619,361855,595.97,45934.42,...,0.7220,900274.58125,1.092303,2.117358,1.364610,2.065617,1.480394,2.053948,10.174230,6.0
2720,Lages,Lages,SC,-50.330222,-27.817259,911.43,2637.660,157349,59.56,32011.96,...,0.6970,900274.58125,2.250184,2.117358,0.074195,2.065617,1.052287,2.053948,9.613588,7.0
2638,AP de Canoinhas/SC,Canoinhas,SC,-50.397849,-26.178807,776.63,1148.036,54480,46.27,29051.81,...,0.6920,900274.58125,2.250184,2.117358,-0.200169,2.065617,0.966666,2.053948,9.253603,8.0
2817,AP de São Bento do Sul - Rio Negrinho/SC,São Bento do Sul,SC,-49.386979,-26.249485,859.92,495.772,85421,149.11,36126.71,...,0.7190,900274.58125,0.980896,2.117358,0.455574,2.065617,1.429022,2.053948,9.102413,9.0
2628,Caçador,Caçador,SC,-51.019035,-26.775348,890.70,983.424,79313,71.89,39751.41,...,0.6200,900274.58125,2.250184,2.117358,0.791532,2.065617,-0.266283,2.053948,9.012356,10.0

In [19]:
cidades_SC.sort_values(by='ranking', ascending=False)[0:10]

,regiao_imediata,cidade,estado,longitude,latitude,altitude,area_territorial_x,populacao_estimada_x,densidade_demografica,pib_per_capita_x,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
2662,Xanxerê,Entre Rios,SC,-52.562534,-26.723621,516.65,103.888,3218,28.87,14789.70,...,0.5500,51.31,-0.930028,-0.787048,-1.522065,-0.817147,-1.464983,-0.907155,-6.428424,290.0
2744,Videira,Monte Carlo,SC,-50.974105,-27.217679,978.53,191.278,9906,48.12,14007.04,...,0.5110,159818.46,-0.503892,-0.270845,-1.594606,-0.690015,-2.132830,-0.381633,-5.573820,289.0
2805,AP de Chapecó/SC,Saltinho,SC,-53.058631,-26.608559,650.02,156.568,3754,25.30,18631.33,...,0.5510,67.10,-0.673147,-0.745678,-1.166000,-0.620984,-1.447858,-0.907103,-5.560770,288.0
2800,Lages,Rio Rufino,SC,-49.777592,-27.863235,890.44,282.571,2483,8.62,20142.27,...,0.5300,49973.96,-0.058725,-0.843778,-1.025957,-1.025159,-1.807468,-0.742944,-5.504031,287.0
2644,Lages,Cerro Negro,SC,-50.870062,-27.795828,1008.76,418.544,3068,8.58,22220.46,...,0.4895,85.00,0.604313,-0.798626,-0.833338,-0.923593,-2.501002,-0.907044,-5.359290,286.0
2701,AP de Chapecó/SC,Irati,SC,-52.895011,-26.657227,433.91,77.912,1909,26.78,17606.31,...,0.6090,39320.76,-1.056693,-0.888081,-1.261005,-0.720750,-0.454650,-0.777986,-5.159164,285.0
2813,AP de Chapecó/SC,Santa Terezinha do Progresso,SC,-53.199847,-26.619776,420.19,119.653,2372,24.38,19342.60,...,0.5850,46815.05,-0.853154,-0.852345,-1.100075,-0.731139,-0.865633,-0.753335,-5.155680,284.0
2733,AP de Florianópolis/SC,Major Gercino,SC,-48.953354,-27.418660,50.98,306.058,3454,11.48,13542.33,...,0.5630,46.24,0.055803,-0.768833,-1.637678,-0.654263,-1.242367,-0.907171,-5.154509,283.0
2843,AP de Chapecó/SC,Sul Brasil,SC,-52.964205,-26.736936,406.51,113.125,2423,24.51,20183.65,...,0.5950,82.18,-0.884986,-0.848409,-1.022122,-0.783004,-0.694390,-0.907053,-5.139964,282.0
2668,AP de Chapecó/SC,Formosa do Sul,SC,-52.793450,-26.648523,467.40,100.408,2495,25.98,19503.50,...,0.5930,51.70,-0.946997,-0.842852,-1.085162,-0.628709,-0.728638,-0.907153,-5.139511,281.0

#outros

In [20]:
regioes = cidades.groupby(['estado','regiao_imediata'])[
    ['area_territorial', 'populacao_estimada', 'pib_per_capita', 'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']
    ].mean().reset_index().copy()
regioes

,estado,regiao_imediata,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
0,AC,API de Cobija/Bolívia - Brasiléia/Brasil,3515.149333,17644.000000,17978.256667,5046.840710,0.498000,135684.486667
1,AC,Cruzeiro do Sul,6388.982600,31854.800000,11518.646000,4978.054280,0.472600,349202.568000
2,AC,Rio Branco,8688.114500,48733.142857,13965.113571,14880.416255,0.435143,185996.187857
3,AL,AP de Maceió/AL,233.634953,44988.209302,16793.270930,9096.449399,0.458163,753781.115349
4,AL,AP de Penedo/AL,465.646500,40847.000000,15125.790000,6566.773315,0.507500,559484.970000
...,...,...,...,...,...,...,...,...
466,TO,Barreiras,2341.909000,16825.000000,13719.940000,6178.088230,0.497000,219249.620000
467,TO,Gurupi,3057.372800,11742.533333,28043.747333,5048.537962,0.579133,286922.452667
468,TO,Palmas,2451.908683,13716.170732,16678.239756,6082.296166,0.528439,67155.964390
469,TO,Paraíso do Tocantins,2614.753938,8291.000000,19530.604375,1754.505953,0.554562,169743.736250
470,TO,Porto Nacional,2132.837000,10628.375000,25639.343750,3852.892429,0.575625,253035.886250

In [21]:
regioes_SC = regioes[regioes['estado'] == 'SC']
regioes_SC

,estado,regiao_imediata,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
362,SC,AP de Araranguá/SC,216.974857,17206.428571,28226.607143,4742.194443,0.653143,1.838872e+05
363,SC,AP de Blumenau/SC,310.982000,66161.111111,40843.583333,24960.888051,0.646444,2.571007e+06
364,SC,AP de Brusque/SC,271.344200,44151.600000,40493.784000,18992.595600,0.645200,1.200622e+06
365,SC,AP de Canoinhas/SC,660.257500,22091.000000,32212.397500,11095.720630,0.636500,6.388975e+05
366,SC,AP de Chapecó/SC,174.647610,12138.609756,30440.291220,6435.848883,0.640537,2.090464e+05
367,SC,AP de Criciúma/SC,233.793385,33809.307692,38681.436923,14837.848654,0.678308,4.040279e+05
368,SC,AP de Florianópolis/SC,359.023833,63855.055556,27949.520000,21412.620039,0.628444,1.820355e+06
369,SC,AP de Imbituba/SC,328.505500,16763.500000,20678.605000,9554.831610,0.599000,3.257843e+05
370,SC,AP de Itajaí - Balneário Camboriú/SC,151.299857,68931.142857,48341.028571,51794.856353,0.649429,3.308821e+06
371,SC,AP de Itapema/SC,75.941500,44635.000000,37154.510000,13760.611835,0.693500,1.232207e+06
372,SC,AP de Jaraguá do Sul/SC,348.773000,56438.600000,36084.818000,40734.659436,0.705400,2.108942e+03
373,SC,AP de Joaçaba - Herval d´Oeste/SC,353.230722,10061.166667,38003.548889,7349.790327,0.651278,3.182208e+05
374,SC,AP de Joinville/SC,477.634667,123604.000000,57459.150000,79779.933007,0.663833,5.578444e+06
375,SC,AP de Mafra/SC - Rio Negro/PR,1006.776750,26508.000000,27448.207500,9371.870030,0.628250,6.976410e+05
376,SC,AP de Pato Branco/PR,166.098667,6070.000000,26131.100000,4198.922693,0.617167,1.806829e+05
377,SC,AP de Rio do Sul/SC,269.260241,10461.965517,28607.547241,4950.360978,0.623483,1.960984e+05
378,SC,AP de Sombrio/SC,181.865000,12999.600000,20450.194000,4229.785796,0.616000,1.113860e+05
379,SC,AP de São Bento do Sul - Rio Negrinho/SC,634.136000,46632.333333,33370.896667,33082.355297,0.674333,1.345419e+06
380,SC,AP de Torres/RS,92.638000,9048.000000,16729.950000,1626.300700,0.618000,1.232100e+05
381,SC,AP de Tubarão - Laguna/SC,209.337267,20423.666667,28225.020000,6680.171549,0.669467,5.527054e+05
382,SC,AP de União da Vitória/PR - Porto União/SC,624.622667,16437.333333,21791.156667,8356.905823,0.610667,2.197897e+05
383,SC,Caçador,683.764800,20894.000000,25017.832000,10107.350676,0.551000,6.574253e+05
384,SC,Concórdia,220.633182,11146.454545,41667.071818,8973.566333,0.668273,1.070511e+05
385,SC,Curitibanos,555.618167,11694.500000,30628.558333,6108.511503,0.583000,3.190015e+05
386,SC,Francisco Beltrão,396.294000,10445.000000,27602.856667,5484.696847,0.609000,7.346768e+04
387,SC,Lages,894.380000,15991.833333,28505.202222,6379.619043,0.567000,4.773303e+05
388,SC,São Miguel do Oeste,178.741550,7910.750000,28080.868500,4035.128092,0.637600,2.368942e+05
389,SC,Timbó,361.570500,18168.750000,30900.952500,9139.100147,0.646250,5.833513e+05
390,SC,Videira,234.861700,13178.100000,33487.742000,9459.708127,0.645900,4.369414e+05
391,SC,Xanxerê,289.745600,10156.900000,32187.515000,3905.208480,0.603400,2.895268e+05

In [22]:
colunas = ['area_territorial', 'populacao_estimada', 'pib_per_capita', 'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']
sel = colunas
regioesz = regioes_SC[sel].copy()
listaz = []
for coluna in colunas:
    if (coluna != "estado") & (coluna != "regiao_imediata"):
        print(coluna)
        listaz.insert(0, 'z_'+coluna)
        media = regioesz[coluna].mean()
        dp = regioesz[coluna].std()
        regioesz['z_'+coluna] = regioesz[coluna].apply(lambda x : (x - media) / dp)
regioesz['totalz'] = regioesz[listaz].sum(axis=1)
regioesz['ranking'] = regioesz['totalz'].rank(ascending=False)
regioesz

area_territorial
populacao_estimada
pib_per_capita
saldo_receitas_despesas
IDHM_Educacao
GDP

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
362,216.974857,17206.428571,28226.607143,4742.194443,0.653143,1.838872e+05,-0.642613,-0.423401,-0.433393,-0.591562,0.510054,-0.534931,-2.115846,19.0
363,310.982000,66161.111111,40843.583333,24960.888051,0.646444,2.571007e+06,-0.235674,1.450573,1.049770,0.607392,0.318285,1.493603,4.683950,4.0
364,271.344200,44151.600000,40493.784000,18992.595600,0.645200,1.200622e+06,-0.407258,0.608054,1.008650,0.253477,0.282658,0.329073,2.074654,6.0
365,660.257500,22091.000000,32212.397500,11095.720630,0.636500,6.388975e+05,1.276274,-0.236421,0.035148,-0.214802,0.033587,-0.148271,0.745515,11.0
366,174.647610,12138.609756,30440.291220,6435.848883,0.640537,2.090464e+05,-0.825840,-0.617396,-0.173168,-0.491129,0.149150,-0.513551,-2.471934,21.0
367,233.793385,33809.307692,38681.436923,14837.848654,0.678308,4.040279e+05,-0.569809,0.212154,0.795603,0.007103,1.230495,-0.347859,1.327687,10.0
368,359.023833,63855.055556,27949.520000,21412.620039,0.628444,1.820355e+06,-0.027710,1.362298,-0.465966,0.396982,-0.197035,0.855711,1.924281,8.0
369,328.505500,16763.500000,20678.605000,9554.831610,0.599000,3.257843e+05,-0.159818,-0.440356,-1.320684,-0.306176,-1.039997,-0.414349,-3.681380,27.0
370,151.299857,68931.142857,48341.028571,51794.856353,0.649429,3.308821e+06,-0.926908,1.556609,1.931117,2.198627,0.403718,2.120584,7.283748,2.0
371,75.941500,44635.000000,37154.510000,13760.611835,0.693500,1.232207e+06,-1.253120,0.626559,0.616108,-0.056776,1.665434,0.355914,1.954119,7.0
372,348.773000,56438.600000,36084.818000,40734.659436,0.705400,2.108942e+03,-0.072084,1.078398,0.490363,1.542765,2.006118,-0.689403,4.356157,5.0
373,353.230722,10061.166667,38003.548889,7349.790327,0.651278,3.182208e+05,-0.052787,-0.696920,0.715916,-0.436933,0.456658,-0.420776,-0.434843,13.0
374,477.634667,123604.000000,57459.150000,79779.933007,0.663833,5.578444e+06,0.485734,3.649474,3.002980,3.858121,0.816110,4.049272,15.861690,1.0
375,1006.776750,26508.000000,27448.207500,9371.870030,0.628250,6.976410e+05,2.776290,-0.067339,-0.524897,-0.317025,-0.202602,-0.098352,1.566076,9.0
376,166.098667,6070.000000,26131.100000,4198.922693,0.617167,1.806829e+05,-0.862846,-0.849701,-0.679727,-0.623777,-0.519905,-0.537654,-4.073610,28.0
377,269.260241,10461.965517,28607.547241,4950.360978,0.623483,1.960984e+05,-0.416279,-0.681577,-0.388613,-0.579218,-0.339082,-0.524554,-2.929324,23.0
378,181.865000,12999.600000,20450.194000,4229.785796,0.616000,1.113860e+05,-0.794597,-0.584437,-1.347534,-0.621947,-0.553306,-0.596541,-4.498362,29.0
379,634.136000,46632.333333,33370.896667,33082.355297,0.674333,1.345419e+06,1.163199,0.703016,0.171333,1.088989,1.116714,0.452119,4.695369,3.0
380,92.638000,9048.000000,16729.950000,1626.300700,0.618000,1.232100e+05,-1.180844,-0.735704,-1.784860,-0.776332,-0.496048,-0.586493,-5.560280,30.0
381,209.337267,20423.666667,28225.020000,6680.171549,0.669467,5.527054e+05,-0.675675,-0.300246,-0.433580,-0.476641,0.977386,-0.221515,-1.130271,15.0
382,624.622667,16437.333333,21791.156667,8356.905823,0.610667,2.197897e+05,1.122017,-0.452842,-1.189900,-0.377212,-0.705993,-0.504422,-2.108351,18.0
383,683.764800,20894.000000,25017.832000,10107.350676,0.551000,6.574253e+05,1.378032,-0.282241,-0.810595,-0.273412,-2.414184,-0.132526,-2.534926,22.0
384,220.633182,11146.454545,41667.071818,8973.566333,0.668273,1.070511e+05,-0.626777,-0.655375,1.146574,-0.340645,0.943205,-0.600225,-0.133243,12.0
385,555.618167,11694.500000,30628.558333,6108.511503,0.583000,3.190015e+05,0.823310,-0.634396,-0.151037,-0.510540,-1.498059,-0.420113,-2.390836,20.0
386,396.294000,10445.000000,27602.856667,5484.696847,0.609000,7.346768e+04,0.133626,-0.682227,-0.506717,-0.547532,-0.753708,-0.628763,-2.985322,24.0
387,894.380000,15991.833333,28505.202222,6379.619043,0.567000,4.773303e+05,2.289746,-0.469895,-0.400644,-0.494464,-1.956122,-0.285568,-1.316947,17.0
388,178.741550,7910.750000,28080.868500,4035.128092,0.637600,2.368942e+05,-0.808118,-0.779237,-0.450525,-0.633490,0.065079,-0.489886,-3.096178,26.0
389,361.570500,18168.750000,30900.952500,9139.100147,0.646250,5.833513e+05,-0.016686,-0.386563,-0.119016,-0.330829,0.312719,-0.195473,-0.735848,14.0
390,234.861700,13178.100000,33487.742000,9459.708127,0.645900,4.369414e+05,-0.565184,-0.577604,0.185069,-0.311817,0.302699,-0.319890,-1.286728,16.0
391,289.745600,10156.900000,32187.515000,3905.208480,0.603400,2.895268e+05,-0.327602,-0.693255,0.032223,-0.641194,-0.914030,-0.445160,-2.989018,25.0

In [23]:
regioes_SC = regioes_SC.merge(regioesz, right_index=True, left_index=True, how = 'left')
regioes_SC

,estado,regiao_imediata,area_territorial_x,populacao_estimada_x,pib_per_capita_x,saldo_receitas_despesas_x,IDHM_Educacao_x,GDP_x,area_territorial_y,populacao_estimada_y,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
362,SC,AP de Araranguá/SC,216.974857,17206.428571,28226.607143,4742.194443,0.653143,1.838872e+05,216.974857,17206.428571,...,0.653143,1.838872e+05,-0.642613,-0.423401,-0.433393,-0.591562,0.510054,-0.534931,-2.115846,19.0
363,SC,AP de Blumenau/SC,310.982000,66161.111111,40843.583333,24960.888051,0.646444,2.571007e+06,310.982000,66161.111111,...,0.646444,2.571007e+06,-0.235674,1.450573,1.049770,0.607392,0.318285,1.493603,4.683950,4.0
364,SC,AP de Brusque/SC,271.344200,44151.600000,40493.784000,18992.595600,0.645200,1.200622e+06,271.344200,44151.600000,...,0.645200,1.200622e+06,-0.407258,0.608054,1.008650,0.253477,0.282658,0.329073,2.074654,6.0
365,SC,AP de Canoinhas/SC,660.257500,22091.000000,32212.397500,11095.720630,0.636500,6.388975e+05,660.257500,22091.000000,...,0.636500,6.388975e+05,1.276274,-0.236421,0.035148,-0.214802,0.033587,-0.148271,0.745515,11.0
366,SC,AP de Chapecó/SC,174.647610,12138.609756,30440.291220,6435.848883,0.640537,2.090464e+05,174.647610,12138.609756,...,0.640537,2.090464e+05,-0.825840,-0.617396,-0.173168,-0.491129,0.149150,-0.513551,-2.471934,21.0
367,SC,AP de Criciúma/SC,233.793385,33809.307692,38681.436923,14837.848654,0.678308,4.040279e+05,233.793385,33809.307692,...,0.678308,4.040279e+05,-0.569809,0.212154,0.795603,0.007103,1.230495,-0.347859,1.327687,10.0
368,SC,AP de Florianópolis/SC,359.023833,63855.055556,27949.520000,21412.620039,0.628444,1.820355e+06,359.023833,63855.055556,...,0.628444,1.820355e+06,-0.027710,1.362298,-0.465966,0.396982,-0.197035,0.855711,1.924281,8.0
369,SC,AP de Imbituba/SC,328.505500,16763.500000,20678.605000,9554.831610,0.599000,3.257843e+05,328.505500,16763.500000,...,0.599000,3.257843e+05,-0.159818,-0.440356,-1.320684,-0.306176,-1.039997,-0.414349,-3.681380,27.0
370,SC,AP de Itajaí - Balneário Camboriú/SC,151.299857,68931.142857,48341.028571,51794.856353,0.649429,3.308821e+06,151.299857,68931.142857,...,0.649429,3.308821e+06,-0.926908,1.556609,1.931117,2.198627,0.403718,2.120584,7.283748,2.0
371,SC,AP de Itapema/SC,75.941500,44635.000000,37154.510000,13760.611835,0.693500,1.232207e+06,75.941500,44635.000000,...,0.693500,1.232207e+06,-1.253120,0.626559,0.616108,-0.056776,1.665434,0.355914,1.954119,7.0
372,SC,AP de Jaraguá do Sul/SC,348.773000,56438.600000,36084.818000,40734.659436,0.705400,2.108942e+03,348.773000,56438.600000,...,0.705400,2.108942e+03,-0.072084,1.078398,0.490363,1.542765,2.006118,-0.689403,4.356157,5.0
373,SC,AP de Joaçaba - Herval d´Oeste/SC,353.230722,10061.166667,38003.548889,7349.790327,0.651278,3.182208e+05,353.230722,10061.166667,...,0.651278,3.182208e+05,-0.052787,-0.696920,0.715916,-0.436933,0.456658,-0.420776,-0.434843,13.0
374,SC,AP de Joinville/SC,477.634667,123604.000000,57459.150000,79779.933007,0.663833,5.578444e+06,477.634667,123604.000000,...,0.663833,5.578444e+06,0.485734,3.649474,3.002980,3.858121,0.816110,4.049272,15.861690,1.0
375,SC,AP de Mafra/SC - Rio Negro/PR,1006.776750,26508.000000,27448.207500,9371.870030,0.628250,6.976410e+05,1006.776750,26508.000000,...,0.628250,6.976410e+05,2.776290,-0.067339,-0.524897,-0.317025,-0.202602,-0.098352,1.566076,9.0
376,SC,AP de Pato Branco/PR,166.098667,6070.000000,26131.100000,4198.922693,0.617167,1.806829e+05,166.098667,6070.000000,...,0.617167,1.806829e+05,-0.862846,-0.849701,-0.679727,-0.623777,-0.519905,-0.537654,-4.073610,28.0
377,SC,AP de Rio do Sul/SC,269.260241,10461.965517,28607.547241,4950.360978,0.623483,1.960984e+05,269.260241,10461.965517,...,0.623483,1.960984e+05,-0.416279,-0.681577,-0.388613,-0.579218,-0.339082,-0.524554,-2.929324,23.0
378,SC,AP de Sombrio/SC,181.865000,12999.600000,20450.194000,4229.785796,0.616000,1.113860e+05,181.865000,12999.600000,...,0.616000,1.113860e+05,-0.794597,-0.584437,-1.347534,-0.621947,-0.553306,-0.596541,-4.498362,29.0
379,SC,AP de São Bento do Sul - Rio Negrinho/SC,634.136000,46632.333333,33370.896667,33082.355297,0.674333,1.345419e+06,634.136000,46632.333333,...,0.674333,1.345419e+06,1.163199,0.703016,0.171333,1.088989,1.116714,0.452119,4.695369,3.0
380,SC,AP de Torres/RS,92.638000,9048.000000,16729.950000,1626.300700,0.618000,1.232100e+05,92.638000,9048.000000,...,0.618000,1.232100e+05,-1.180844,-0.735704,-1.784860,-0.776332,-0.496048,-0.586493,-5.560280,30.0
381,SC,AP de Tubarão - Laguna/SC,209.337267,20423.666667,28225.020000,6680.171549,0.669467,5.527054e+05,209.337267,20423.666667,...,0.669467,5.527054e+05,-0.675675,-0.300246,-0.433580,-0.476641,0.977386,-0.221515,-1.130271,15.0
382,SC,AP de União da Vitória/PR - Porto União/SC,624.622667,16437.333333,21791.156667,8356.905823,0.610667,2.197897e+05,624.622667,16437.333333,...,0.610667,2.197897e+05,1.122017,-0.452842,-1.189900,-0.377212,-0.705993,-0.504422,-2.108351,18.0
383,SC,Caçador,683.764800,20894.000000,25017.832000,10107.350676,0.551000,6.574253e+05,683.764800,20894.000000,...,0.551000,6.574253e+05,1.378032,-0.282241,-0.810595,-0.273412,-2.414184,-0.132526,-2.534926,22.0
384,SC,Concórdia,220.633182,11146.454545,41667.071818,8973.566333,0.668273,1.070511e+05,220.633182,11146.454545,...,0.668273,1.070511e+05,-0.626777,-0.655375,1.146574,-0.340645,0.943205,-0.600225,-0.133243,12.0
385,SC,Curitibanos,555.618167,11694.500000,30628.558333,6108.511503,0.583000,3.190015e+05,555.618167,11694.500000,...,0.583000,3.190015e+05,0.823310,-0.634396,-0.151037,-0.510540,-1.498059,-0.420113,-2.390836,20.0
386,SC,Francisco Beltrão,396.294000,10445.000000,27602.856667,5484.696847,0.609000,7.346768e+04,396.294000,10445.000000,...,0.609000,7.346768e+04,0.133626,-0.682227,-0.506717,-0.547532,-0.753708,-0.628763,-2.985322,24.0
387,SC,Lages,894.380000,15991.833333,28505.202222,6379.619043,0.567000,4.773303e+05,894.380000,15991.833333,...,0.567000,4.773303e+05,2.289746,-0.469895,-0.400644,-0.494464,-1.956122,-0.285568,-1.316947,17.0
388,SC,São Miguel do Oeste,178.741550,7910.750000,28080.868500,4035.128092,0.637600,2.368942e+05,178.741550,7910.750000,...,0.637600,2.368942e+05,-0.808118,-0.779237,-0.450525,-0.633490,0.065079,-0.489886,-3.096178,26.0
389,SC,Timbó,361.570500,18168.750000,30900.952500,9139.100147,0.646250,5.833513e+05,361.570500,18168.750000,...,0.646250,5.833513e+05,-0.016686,-0.386563,-0.119016,-0.330829,0.312719,-0.195473,-0.735848,14.0
390,SC,Videira,234.861700,13178.100000,33487.742000,9459.708127,0.645900,4.369414e+05,234.861700,13178.100000,...,0.645900,4.369414e+05,-0.565184,-0.577604,0.185069,-0.311817,0.302699,-0.319890,-1.286728,16.0
391,SC,Xanxerê,289.745600,10156.900000,32187.515000,3905.208480,0.603400,2.895268e+05,289.745600,10156.900000,...,0.603400,2.895268e+05,-0.327602,-0.693255,0.032223,-0.641194,-0.914030,-0.445160,-2.989018,25.0

In [24]:
regioes_SC.sort_values(by='ranking')[1:4]

,estado,regiao_imediata,area_territorial_x,populacao_estimada_x,pib_per_capita_x,saldo_receitas_despesas_x,IDHM_Educacao_x,GDP_x,area_territorial_y,populacao_estimada_y,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
370,SC,AP de Itajaí - Balneário Camboriú/SC,151.299857,68931.142857,48341.028571,51794.856353,0.649429,3.308821e+06,151.299857,68931.142857,...,0.649429,3.308821e+06,-0.926908,1.556609,1.931117,2.198627,0.403718,2.120584,7.283748,2.0
379,SC,AP de São Bento do Sul - Rio Negrinho/SC,634.136000,46632.333333,33370.896667,33082.355297,0.674333,1.345419e+06,634.136000,46632.333333,...,0.674333,1.345419e+06,1.163199,0.703016,0.171333,1.088989,1.116714,0.452119,4.695369,3.0
363,SC,AP de Blumenau/SC,310.982000,66161.111111,40843.583333,24960.888051,0.646444,2.571007e+06,310.982000,66161.111111,...,0.646444,2.571007e+06,-0.235674,1.450573,1.049770,0.607392,0.318285,1.493603,4.683950,4.0

In [26]:
regioes_SC.sort_values(by='ranking', ascending=False)[0:3]

,estado,regiao_imediata,area_territorial_x,populacao_estimada_x,pib_per_capita_x,saldo_receitas_despesas_x,IDHM_Educacao_x,GDP_x,area_territorial_y,populacao_estimada_y,...,IDHM_Educacao_y,GDP_y,z_area_territorial,z_populacao_estimada,z_pib_per_capita,z_saldo_receitas_despesas,z_IDHM_Educacao,z_GDP,totalz,ranking
380,SC,AP de Torres/RS,92.638000,9048.0,16729.950,1626.300700,0.618000,123209.980,92.638000,9048.0,...,0.618000,123209.980,-1.180844,-0.735704,-1.784860,-0.776332,-0.496048,-0.586493,-5.560280,30.0
378,SC,AP de Sombrio/SC,181.865000,12999.6,20450.194,4229.785796,0.616000,111386.026,181.865000,12999.6,...,0.616000,111386.026,-0.794597,-0.584437,-1.347534,-0.621947,-0.553306,-0.596541,-4.498362,29.0
376,SC,AP de Pato Branco/PR,166.098667,6070.0,26131.100,4198.922693,0.617167,180682.855,166.098667,6070.0,...,0.617167,180682.855,-0.862846,-0.849701,-0.679727,-0.623777,-0.519905,-0.537654,-4.073610,28.0